name: Custom CDK Devnets

on:
  push:

# please goddd
jobs:
  regression_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Regression Tests
        uses: 0xPolygon/kurtosis-cdk@v0.1.9
        with:
          zkevm_bridge_service: '2e28fe4'